# Generated by Django 3.1.6 on 2021-02-07 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_profile_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='images',
        ),
    ]
