# Generated by Django 3.1.6 on 2021-02-10 12:11

from django.db import migrations, models
import mysite.models.profile_models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_remove_profile_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='images',
            field=models.ImageField(blank=True, default='', upload_to=mysite.models.profile_models.upload_image_to),
        ),
    ]
