# Generated by Django 3.1.6 on 2021-02-10 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_profile_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='images',
            new_name='image',
        ),
    ]
